---
title: ""
output:  
  html_document:
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: yes
      toc_depth: 3
---
<br><br>



[CV in PDF format (updated 20.2.2018)](https://github.com/saaralonbarkat/personal-site/raw/master/SAAR%20ALON%20BARKAT%20CV%220.2.18.pdf) 


---




###Personal details

Name: Saar Alon-Barkat

E-mail: [saar.barkat@mail.huji.ac.il](mailto:saar.barkat@mail.huji.ac.il) 

ORCID ID: [0000-0002-3342-0568](http://orcid.org/0000-0002-3342-0568)

<br><br>

---


###Education

Years        |Description
-------------|---------------------------------------------------------------------------
2014-present |Ph.D. candidate in Public Administration at the department of Political Science at the Hebrew University of Jerusalem. Academic Supervisor: Prof. Sharon Gilad.
.            |Dissertation title: *The symbolic aspects of government bureaucracies' public communications, and its influence on citizens' attitudes*.
2012-2014    |M.A. *Summa cum Laude in Political Science, at the department of Political Science at the Hebrew University of Jerusalem (advanced graduate studies program). Academic supervisor: Prof. Sharon Gilad.
.            |M.A. thesis title: *Political control and organizations' symbolic responses to bottom-up public pressures*.
2007-2011    |LL.B. *Magna cum Laude* in Law and Political Science, at the Hebrew University of Jerusalem.


---


###Publications


Gilad, Sharon, and Saar Alon-Barkat. In Press, 2017. "Enhancing Democracy via Bureaucracy: Senior managers' Social Identificaties and Motivation for Policy Change". *Governance*. DOI: [10.1111/gove.12300](https://doi.org/10.1111/gove.12300).  

Alon-Barkat, Saar, and Sharon Gilad. 2017. "Compensating for Poor Performance with Promotional Symbols: Evidence from a Survey Experiment". *Journal of Public Administration Research and Theory*. 27(4): 661-675. DOI: [10.1093/jopart/mux013](https://doi.org/10.1093/jopart/mux013).  

Gilad, Sharon, Saar Alon-Barkat, and Alexandr Braverman. 2016. "Large-Scale Social Protest: A Business Risk and a Bureaucratic Opportunity". *Governance* 29(3): 371-392. DOI: [10.1111/gove.12173](https://doi.org/10.1111/gove.12173).  

Alon-Barkat, Saar, and Sharon Gilad. 2016. "Political control or legitimacy deficit? Bureaucracies' symbolic responses to bottom-up public pressures". *Policy & Politics* 44(1): 41-58. DOI: [10.1332/030557315x14443003393944](https://doi.org/10.1332/030557315x14443003393944)



---


###Working papers

Gilad, Sharon, Saar Alon-Barkat, and Chagai Weiss. "Government Translation of Social Movements’ Agendas and its Shaping by Bureucratic Politics". Work in progress (submitted for publication).


Saar Alon-Barkat. "The effects of symbols and information in government public communication on citizens' trust: Evidence from a survey experiment". Work in progress.


Alon-Barkat, Saar. "Bureaucracies' Shaping of Citizens' Attitudes: Functional, Informational, Procedural-Fairness and Symbolic Effect". Work in progress.


Gilad, Sharon and Saar Alon-Barkat. "Civil Servants’ Social Identities as Factor Balancing Between Reputation Seeking and Accountability". Work in progress.




---


###Fellowships

Years        |Description
-------------|---------------------------------------------------------------------------
2014-present |[Azrieli Foundation Fellows program fellowship](http://fellows.azrielifoundation.org/) (68,000 EUROS over three years).
2014-2017    |[Hoffman leadership and responsibility program fellowship](http://hoffman-program.huji.ac.il/page/3), the Hebrew University of Jerusalem (38,000 EUROS over three years).
2012-2017    |[Advanced Graduate Studies program fellowship ("Telem")](http://en.politics.huji.ac.il/book/program-advanced-degrees-telem). The Hebrew University of Jerusalem, the department of Political Science (49,000 EUROS over five years).

*These aforementioned amounts represent the full amount for each fellowship, in separate.*



---


###Prizes and awards

Years        |Description
-------------|---------------------------------------------------------------------------
2016-present |Research grant by the Azrieli Foundation Fellows program fellowship (8,800 EUROS).
2015         |Award for an Outstanding MA Thesis by the Israel Political Science Association (250 EUROS).
2015         |The Nancy & Lawrence E. Glick Prize in Israeli Democracy, for Best MA thesis (1,700 EUROS).
2014         |The Hebrew University's Rector's honor list award for MA students (1,200 EUROS).
2009-2011    |Law Faculty Dean's honor list Awards for BA students for years: 2008, 2009, 2010.


---


###Reviewer for journals 
2017-Present: Public Administration.
2016-Present: Journal of Public Administration Research and Theory.
2016: Governance. 
2015: Regulation & Governance.

See list of reviews in [Publons](https://publons.com/author/1367408/saar-alon-barkat) 

---


###Membership in professional associations:
Structure and Organization of Governance (SOG).
Public Administration Research Association (PMRA).
Midwest Political Science Association (MPSA).
Israel Political Science Association (ISPSA).



---


###Conferences presentations
Saar Alon-Barkat. " The effects of symbols and information in government public communication on citizens' trust: Evidence from a survey experiment". Public Management Research Conference (PMRC), Singapore (June 2018).

Saar Alon-Barkat. "The Effects of Substantive Information and Symbols on Citizens' Attitudes, and Their Moderation by Personal Relevance". 21st Annual IRSPM Conference, Budapest (April 2017).

Saar Alon-Barkat. "The Effects of Substantive Information and Symbols on Citizens' Attitudes, and Their Moderation by Personal Relevance". The 12th Annual Graduate Conference in Political Science, International Relations and Public Policy, Jerusalem (December 2016).

Saar Alon-Barkat and Gilad, Sharon. "Offsetting the Effect of Bad Performance with Promotional Symbols: Evidence from a Survey Experiment". World Congress of Political Science (IPSA), Poznan (July 2016).

Saar Alon-Barkat and Gilad, Sharon. "Offsetting the Effect of Bad Performance with Promotional Symbols: Evidence from a Survey Experiment". Public Management Research Conference (PMRC), Aarhus (June 2016).

Saar Alon-Barkat. "Bureaucracies' Shaping of Citizens' Attitudes: Functional, Informational, Procedural-Fairness and Symbolic Effects". The 11th Annual Graduate Conference in Political Science, International Relations and Public Policy, Jerusalem (December 2015).

Saar Alon-Barkat. "Bureaucracies' Shaping of Citizens' Attitudes: Functional, Informational, Procedural-Fairness and Symbolic Effects". The 73rd Annual Midwest Political Science Association (MPSA) Conference, Chicago (April 2015).

Saar Alon-Barkat. "Distinguishing the Symbolic Dimension in Democratic Responsiveness: Towards a New Research Direction". The 10th Annual Graduate Conference in Political Science, International Relations and Public Policy, Jerusalem (December 2014).

Saar Alon-Barkat and Sharon Gilad. "Political Control or Legitimacy Deficit? Bureaucracies? Symbolic Response to Bottom-Up Public Pressures". 8th ECPR General Conference, Glasgow (September 2014).

Saar Alon-Barkat and Sharon Gilad, "Political Control and Organizations Symbolic Responses to Bottom-Up Public Pressures". 5th Biennial ECPR Standing Group for Regulatory Governance Conference, Barcelona (June 2014).

Sharon Gilad and Saar Alon-Barkat, "A Comparison of Public and Private Organizations? Management of Mass Social Protest via Communications". Paper presented at the 2014 SOG (Structure and Organization of Government) conference, Jerusalem (Jan 2014).

Saar Alon-Barkat, "Designing Universal Measures for Dimensional Publicness". Paper presented at the 2014 SOG (Structure and Organization of Government) conference, Jerusalem (Jan 2014).

Saar Alon Barkat, Tamar Hofnung, "Between State and Private Sector: Battered Women Shelters Policy in Israel". Paper presented at the 15th Annual Conference of the Israeli Political Science Association (ISPSA). Jerusalem (May 2013).



---


###Academic workshops 

Years        |Description
-------------|---------------------------------------------------------------------------
2018         |ECPR Joint sessions of Workshops. Workshop on "Accountability and Reputation". Nicosia, Cyprus.
2017         |Workshop on mismatches between performance and reputation in Governance. Utrecht, Netherlands.
2017         |Successful Public Governance (SPG) workshop. Utrecht, Netherlands.
2015         |Israeli-Canadian Workshop on "Institutions and Individual, Organizational and Field Level Identities", Halbert Center and the Jerusalem School of Business Administration.



---


###Teaching

Years        |Description
-------------|---------------------------------------------------------------------------
2016-2017    |Lecturer, “A theoretical lens on Public Administration" course (graduate, honors program). The Federmann School of Public Policy and Government, Hebrew University of Jerusalem.
2013-2014    |Teaching assistant, “A theoretical lens on Public Administration" course (graduate, honors program). The Federmann School of Public Policy and Government, Hebrew University of Jerusalem.
2013-2015    |Teaching assistant, “Research methods" course (undergraduate). The Department of Political Science, the Hebrew University of Jerusalem.
2012-2014    |Teaching assistant, "Israeli politics" course (undergraduate), The Department of Political Science, the Hebrew University of Jerusalem.
2012-2013    |Teaching assistant, "Introduction to Public Administration" course (undergraduate), The Department of Political Science, the Hebrew University of Jerusalem.
2012-2013    |Teaching assistant, "Academic reading and writing" course (undergraduate), The Department of Political Science, the Hebrew University of Jerusalem.



---


###Academic activities

Years        |Description
-------------|---------------------------------------------------------------------------
2017-present |Co-founder of project [Israeli research in 500 words](https://www.facebook.com/israeliresearch500words/): an online platform enabling Israeli academic scholars to communicate their researches with Israeli non-academic audiences. 
2017-present |Founder and coordinator of a study group of Hebrew University graduate students on "R" (open source software environment for statistical computing and graphics).
2015-2016    |Co-founder and coordinator of a study group of Hebrew University graduate students ("Limud BeChevruta") on "Politics Now: Issues and Dilemmas in the Political Research of Contemporary Events".
2015         |Co-organizer of a full-day workshop for Political Science graduate students, facilitated by Dr. Guy Grossman (University of Pennsylvania).
2015-present |Co-founder and coordinator of the Israeli Public Administration and Public Policy researchers' inter-university forum.




---



###Professional experience in government public administration


Years        |Description
-------------|---------------------------------------------------------------------------
2017         |Member of a "Nudge" policy pilot project, in collaboration with Jerusalem municipality and the Ministry of Finance. As a part of "Nudgethon", government-academia collaborative initiative on nudge policy solutions. 
2012         |Employee at the Israeli Prime Minister's Office, the Department of Governance and Policy Planning.
2011-2012    |Employee at the Ministry of Justice. Legal internship at the Attorney General of the state of Israel, Adv. Yehuda Weinstein. 



---



###Non-academic voluntary activities

Years        |Description
-------------|---------------------------------------------------------------------------
2012-present |Active Volunteering at the "The Public Knowledge Workshop", Israeli non-profit organization working to make public information accessible to citizens using open sourced digital projects. Developer and data analyst in the ["Budget-key project"](www.obudget.org), which aims to make information on government spending accessible to the public.



---












